name: Run Script 4 Times a Day

on:
  # schedule:
  #   # Runs at 00:00, 06:00, 12:00, and 18:00 UTC
  #   - cron: "0 0,6,12,18 * * *"
  workflow_dispatch

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Specify the Python version you need

      # Step 3: Install dependencies and font style
      - name: Install dependencies
        run: |
          pip install bs4
          pip install openpyxl
          pip install pillow
          pip install pandas
          pip install requests
          sudo apt-get install -y fonts-dejavu

      # Step 4: Run the script
      - name: Execute script
        run: python main.py

      # Step 5: Upload the generated collage as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: generate-collage
          path: task1_*.png  # Matches the naming format in your script

      # Step 6: Upload task2 files as artifacts
      - name: Upload task2 files
        uses: actions/upload-artifact@v3
        with:
          name: generate-xlsx
          path: task2_*.xlsx 
